src/kudapoyti.Web/Areas/Admin/Controllers/PlaceController.cs
using kudapoyti.Service.Common.Utils;
using kudapoyti.Service.Dtos;
using kudapoyti.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace kudapoyti.Web.Areas.Admin.Controllers
{
    [Area("admin")]
    [Route("admins/place")]
    public class PlaceController : Controller
    {
        private readonly IPlaceService _place;
        private readonly int _pageSize = 5;
        public PlaceController(IPlaceService place)
        {
            this._place = place;
        }

        [HttpGet]
        public async Task<ViewResult> Index(int page = 1)
        {
            var products = await _place.GetAllAsync(new PaginationParams(page, _pageSize));
            return View("Index", products);
        }

        [HttpGet("create")]
        public ViewResult Create()
        {
            return View();
        }

        [HttpPost("create")]
        public async Task<IActionResult> CreateAsync(PlaceCreateDto productsDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _place.CreateAsync(productsDto);
                if (result)
                    return RedirectToAction("index", "place", new { area = "admin" });
                return Create();
            }
            return Create();
        }

        [HttpGet("delete")]
        public async Task<ViewResult> Delete(long Id)
        {
            var admin = await _place.GetAsync(Id);
            if (admin != null)
            {
                return View(admin);
            }
            return View();
        }
        [HttpPost("delete")]
        public async Task<IActionResult> DeleteAsync(long Id)
        {
            var admin = await _place.DeleteAsync(Id);
            if (admin) return RedirectToAction("Index", "place", new { area = "admin" });
            return View();
        }
    }
}

src/kudapoyti.Web/Controllers/PlacesController.cs
using kudapoyti.Service.Common.Utils;
using kudapoyti.Service.Dtos.CommentDtos;
using kudapoyti.Service.Interfaces;
using kudapoyti.Service.Interfaces.CommentServices;
using kudapoyti.Service.Services.CommentServices;
using kudapoyti.Service.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace kudapoyti.Web.Controllers;

[Route("places")]
public class PlacesController : Controller
{
    private readonly IPlaceService _place;
    private readonly ICommentService _commentService;
    
    private readonly int _pageSize = 3;
    public PlacesController(IPlaceService place, ICommentService commentService)
    {
        this._place = place;
        _commentService = commentService;
    }
    
    public async Task<ViewResult> Index(int page = 1)
    {
        var products = await _place.GetAllAsync(new PaginationParams(page, _pageSize));
        var places = await _place.GetTopPLacesAsync(new PaginationParams(page, _pageSize));
        var tuple=new Tuple<PagedList<PlaceBaseViewModel>,PagedList<PlaceViewModel>>(products, places);
        return View("Index", tuple);
    }
    [HttpGet("{placeId}")]
    public async Task<ViewResult> GetAsync(long placeId, CommentCreateDto commentDto, int page=1)
    {
        var place = await _place.GetAsync(placeId);
        commentDto.PlaceId=placeId;
        var placetype = await _place.GetByTypeAsync(new PaginationParams(page,_pageSize), place.PlaceSiteUrl);
        var get = await _commentService.GetByPlaceId(commentDto.PlaceId, new PaginationParams(page, _pageSize));
        var tuple = new Tuple<PlaceViewModel, PagedList<PlaceViewModel>,PagedList<CommentsViewModel>>(place, placetype,get);
        return View(tuple);
    }

    [HttpGet("comment")]
    public async Task<ViewResult> Comment(long PlaceId,CommentCreateDto commentCreateDto)
    {
        commentCreateDto.PlaceId = PlaceId;
        return View("comment", commentCreateDto);
    }


    [HttpPost("create")]
    public async Task<IActionResult> CreateCommentAsync(CommentCreateDto commentCreateDto)
         {
        if (ModelState.IsValid)
        {
            var comments = await _commentService.CreateAsync(commentCreateDto);
            if (comments)
            {
                return RedirectToAction("index", "places", new { area = "" });
            }
            else return RedirectToAction("comment", "places", new { area = "" });

        }
        else return RedirectToAction("comment", "places", new { area = "" });       
    }
    [HttpGet("region")]
    public async Task<ViewResult> GetRegion(string SityName)
    {

        var region = (await _place.GetByCityAsync(SityName));
        return View("regionType",region);

    }

}

src/kudapoyti.Web/Views/Places/Comment.cshtml
@using kudapoyti.Service.Common.Utils
@using kudapoyti.Service.Dtos.CommentDtos
@model  CommentCreateDto
@{
    Layout = "_GetLayout.cshtml";
}
<style>

    .wrppr {
        padding: 10px 50px 20px;
        border-radius: 50px;
        background-color: rgba(240, 255, 255, .5);
    }
</style>
<div class="wrppr">
        <h2 class="text-uppercase text-center mb-4">Comment</h2>
        <form asp-controller="Places" asp-action="create" asp-route-PlaceId="@Model.PlaceId" method="post">
            <div class="form-outline">
                <input type="text" asp-for=UserName class="form-control form-control-md" placeholder="Enter your fullname" style="border-radius: 20px; width:30%" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-outline mb-2">
            <textarea class="form-control text-dark" asp-for=Comments id="textAreaExample6" rows="3" placeholder="comment" style="border-radius: 15px"></textarea>
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="mt-3">
            <input type="submit" class="btn btn-success" style="width:100%; border-radius: 20px" value="Comment"  />
            </div>

            <a class="btn btn-primary btn-block mt-3 " asp-controller="places" asp-action="@Model.PlaceId" style="border-radius: 20px">
                Exit
            </a>
        </form> 
</div>

src/kudapoyti.Web/Views/Places/Get.cshtml
@using kudapoyti.Service.Common.Utils
@using kudapoyti.Service.ViewModels
@model Tuple<PlaceViewModel, PagedList<PlaceViewModel>,PagedList<CommentsViewModel>>

@{
    Layout = "_GetLayout.cshtml";
}

<div id="PlaceHolderHere"></div>
<section class="cinema">
    <div class="container">
        <div class="cinema-content" style="display: flex; column-gap: 10px;">
            <div class="cinema-content__left" style="width: 70%;">
                <div>
                    <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;" _msttexthash="1849640" _msthash="30">@Model.Item1.PlaceSiteUrl</h6>
                    <h2>@Model.Item1.Title</h2>
                    <img class="img-fluid" src="~/@Model.Item1.ImageUrl" width="704" height="467" style="display: inline-block; width: 100%;">
                </div>
                <div class="container">
                    <dib class="row">
                        <div b-0vlayvk2yn="" class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                            <font b-0vlayvk2yn="" class="d-inline-flex align-items-center">
                                <h6>Published: @Model.Item1.CreatedAt</h6>
                            </font>
                        </div>
                        <font class="col-lg-6 text-center text-lg-right">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z" />
                                <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
                            </svg>
                            @Model.Item1.rank
                        </font>
                    </dib>
                </div>
                <h5 class="text-dark mt-2"><span class="text-primary">Description:  </span>@Model.Item1.Description</h5>

                <a class="m-0" href="@Model.Item1.Location_link">
                    <i class="fa fa-map-marker-alt text-primary mr-2"></i>
                    <font _mstmutation="1" _msttexthash="1386697" _msthash="48">@Model.Item1.Region</font>
                </a>

                <div class="m-0">

                    <font _mstmutation="1" _msttexthash="1386697" _msthash="48">улица Бобура, 174, Шайхантахурский район</font>
                </div>
                <h5 class="mt-5"> написать комментарий!</h5>
                <a class="btn btn-primary btn-block mb-3" style="border-radius: 20px " data-toggle="ajax-modal"
                   asp-action="comment" asp-controller="places" asp-route-PlaceId="@Model.Item1.Id">
                    Create
                </a>
                <div>
                    <div class="rating-stars">
                        <input type="radio" name="rating" id="rs0" checked><label for="rs0"></label>
                        <input type="radio" name="rating" id="rs1"><label for="rs1"></label>
                        <input type="radio" name="rating" id="rs2"><label for="rs2"></label>
                        <input type="radio" name="rating" id="rs3"><label for="rs3"></label>
                        <input type="radio" name="rating" id="rs4"><label for="rs4"></label>
                        <input type="radio" name="rating" id="rs5"><label for="rs5"></label>
                        <span class="rating-counter"></span>
                    </div>
                </div>
                <div class="col-md-12 mt-4 mb-4 pt-2 pb-2 pe-4 px-4">
                    <h3 class="title-5 text-center mt-3">Comment's</h3>
                    <table class="table table-bordered multiselect">
                        <thead class="text-dark">
                            <tr>
                                <th>Name</th>
                                <th>Comment</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var admin in Model.Item3)
                            {
                                <tr class="tr-shadow text-dark">
                                    <td class="name">@admin.UserName</td>
                                    <td class="name">@admin.Comments</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @{
                        if (@Model.Item3.MetaData.HasPrevious)
                        {
                            <div class="page-item">
                                <a class="page-link" style="border-radius:15px;" asp-controller="places" asp-action="get" asp-route-page="@(Model.Item3.MetaData.CurrentPage-1)" aria-label="Previous">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 15 15">
                                        <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z" />
                                    </svg>
                                </a>
                            </div>
                        }
                        else
                        {
                            <div class="page-item disabled">
                                <a class="page-link" href="#" style="border-radius:15px;" aria-label="Previous">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 15 15">
                                        <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z" />
                                    </svg>
                                </a>
                            </div>
                        }
                        if (Model.Item3.MetaData.HasNext)
                        {
                            <div class="page-item">
                                <a class="page-link" style="border-radius:15px;" asp-controller="places" asp-action="get" asp-route-page="@(Model.Item3.MetaData.CurrentPage + 1)" aria-label="Next">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-down text-center" viewBox="0 0 15 15">
                                        <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z" />
                                    </svg>
                                </a>
                            </div>
                        }
                        else
                        {
                            <div class="page-item disabled">
                                <a class="page-link" style="border-radius:15px;" href="#" aria-label="Next">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-down text-center" viewBox="0 0 15 15">
                                        <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z" />
                                    </svg>
                                </a>
                            </div>
                        }
                    }
                </div>
                
            </div>

            <ul class="cinema-content__recommend-list" style="flex-grow: 1; list-style: none; padding-top: 70px; padding-left: 0;">
                @{
                    foreach (var type in Model.Item2)
                    {
                        if (type.Id != Model.Item1.Id)
                        {
                            <a asp-controller="places" asp-action="get" asp-route-placeId="@type.Id">
                            <li class="list__item" style="display:flex; width: 100%; min-height: 220px; position: relative; border-radius: 10px; overflow: hidden;">
                                <img src="/@type.ImageUrl" alt="img" style="display: inline-block; width: 100%; position: absolute; z-index: -1;">
                                <div class="destination-overlay text-white text-decoration-none text-center" href="">
                                    <h5 class="text-white">@type.Title</h5>
                                </div>
                            </li>
                            </a>
                        }
                    }
                }

                @{
                    if (@Model.Item2.MetaData.HasPrevious)
                    {
                        <li class="page-item">
                            <a class="page-link" style="border-radius:15px;" asp-controller="places" asp-action="get" asp-route-page="@(Model.Item2.MetaData.CurrentPage-1)" aria-label="Previous">
                                <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 15 15">
                                    <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z" />
                                </svg>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item disabled">
                            <a class="page-link" href="#" style="border-radius:15px;" aria-label="Previous">
                                <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-up" viewBox="0 0 15 15">
                                    <path d="M3.204 11h9.592L8 5.519 3.204 11zm-.753-.659 4.796-5.48a1 1 0 0 1 1.506 0l4.796 5.48c.566.647.106 1.659-.753 1.659H3.204a1 1 0 0 1-.753-1.659z" />
                                </svg>
                            </a>
                        </li>
                    }
                    if (Model.Item2.MetaData.HasNext)
                    {
                        <li class="page-item">
                            <a class="page-link" style="border-radius:15px;" asp-controller="places" asp-action="get" asp-route-page="@(Model.Item2.MetaData.CurrentPage + 1)" aria-label="Next">
                                <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-down text-center" viewBox="0 0 15 15">
                                    <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z" />
                                </svg>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item disabled">
                            <a class="page-link" style="border-radius:15px;" href="#" aria-label="Next">
                                <svg xmlns="http://www.w3.org/2000/svg" width="ceter" height="25" fill="currentColor" class="bi bi-caret-down text-center" viewBox="0 0 15 15">
                                    <path d="M3.204 5h9.592L8 10.481 3.204 5zm-.753.659 4.796 5.48a1 1 0 0 0 1.506 0l4.796-5.48c.566-.647.106-1.659-.753-1.659H3.204a1 1 0 0 0-.753 1.659z" />
                                </svg>
                            </a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
</section>

src/kudapoyti.Web/Views/Places/RegionType.cshtml
@using kudapoyti.Service.ViewModels
@model List<PlaceViewModel>
<div>
    <div class="text-center mb-50 mt-50">
        <h2 class="text-primary text-uppercase">Recommended</h2>
    </div>
    <div class="row g-5">
        @{
            foreach (var place in Model)
            {
                <div class="col-lg-4 h-300">
                    <div class="mt-5 md-5 me-5">
                        <a asp-controller="places" asp-action="get" asp-route-placeId="@place.Id">
                            <div class="destination-item position-relative overflow-hidden mb-2 ">

                                <img class="img-fluid" src="~/@place.ImageUrl">

                                <div class="destination-overlay text-white text-decoration-none text-center" href="">
                                    <h4 class="text-white">@place.Title</h4>
                                    <span>@place.Region</span>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            }
        }
    </div>
   @* <div class="text-center mb-5 mt-5">
        <h2 class="text-primary text-uppercase">TOP</h2>
    </div>
    <div class="row g-5">
        @{
            foreach (var place in Model.Item2)
            {
                if (place.PlaceSiteUrl == "Park")
                {
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="package-item bg-white mb-2">
                            <a asp-controller="places" asp-action="get" asp-route-placeId="@place.Id">
                                <img class="img-fluid" src="@place.ImageUrl" alt="">
                                <div class="p-4">
                                    <div class="d-flex justify-content-between mb-3">
                                        <small class="m-0"><i class="fa fa-map-marker-alt text-primary mr-2"></i>@place.Region</small>
                                        <small class="m-0"><i class="fa fa-list-alt text-primary mr-2"></i>@place.PlaceSiteUrl</small>
                                    </div>
                                    <a class="h5 text-decoration-none" href="">@place.Title</a>
                                    <div class="border-top mt-4 pt-4">
                                        <div class="d-flex justify-content-between">
                                            <h6 class="m-0"><i class="fa fa-star text-primary mr-2"></i>@place.rank <small>(@place.rankedUsersCount)</small></h6>
                                            <h7 class="m-0">@place.CreatedAt</h7>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>

                }
            }
        }

    </div>
    *@
</div>

src/kudapoyti.Web/Views/Places/_GetLayout.cshtml
<!DOCTYPE html>

<html>
    
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kudapoyti.Web</title>
    <link href="~/Images/favicon.ico" rel="icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <link href="~/css/main.css" rel="stylesheet">
</head>
<body>
    <div class="container-fluid position-relative nav-bar p-3">
        <div class="container-lg position-relative p-2 mt-1">
            <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-1 py-lg-3 pl-1 pl-lg-4">
                <a href="" class="navbar-brand">
                    <h1 class="m-0 text-primary"><span class="text-dark">Kuda</span>Poyti</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0" style="column-gap: 10px;">
                        <button type="button" class="btn btn-outline-success btn-rounded" style="border-radius:15px;" data-mdb-ripple-color="dark">Party</button>
                        <button type="button" class="btn btn-outline-success btn-rounded" style="border-radius:15px;" data-mdb-ripple-color="dark">Kino</button>
                        <button type="button" class="btn btn-outline-success btn-rounded" style="border-radius:15px;" data-mdb-ripple-color="dark">Konsert</button>
                        <button type="button" class="btn btn-outline-success btn-rounded" style="border-radius:15px;" data-mdb-ripple-color="dark">Restaurant</button>
                        <button type="button" class="btn btn-outline-success btn-rounded" style="border-radius:15px;" data-mdb-ripple-color="dark">Place</button>
                    </div>
                </div>
            </nav>
        </div>
    </div>


    <div class="container">
        <main class="pb-3 mt-5">
            @RenderBody()
        </main>
        
    </div>
    <div id="footer" class="container-fluid bg-dark text-white-10 py-5 px-sm-3 px-lg-5" style="margin-top: 50px;">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6 mb-5">
                <a href="" class="navbar-brand">
                    <h1 class="text-primary"><span class="text-white">Kuda</span>Payti</h1>
                </a>


            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Our Services</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>News Service</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Usefull Links</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white-50 mb-2" href="https://t.me/kudapoytii_bot"><i class="fa fa-angle-right mr-2"></i>Admin</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Contact Us</h5>
                <p><i class="fa fa-phone-alt mr-2"></i>+998 71 505 0555</p>
            </div>
        </div>
    </div>

</body>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/main.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>